
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dilki
 */
public class Calculator extends javax.swing.JFrame {
        double firstnum;
        double secondnum;
        double result;
        String operations;
        private Object math;
        
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDisplay = new javax.swing.JTextField();
        jButtonBackspace = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonPlusOrMineze = new javax.swing.JButton();
        jButtonMod = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonMultiple = new javax.swing.JButton();
        jButtonMin = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonLog = new javax.swing.JButton();
        jButtonLnX = new javax.swing.JButton();
        jButtonSquart1 = new javax.swing.JButton();
        jButtonSin = new javax.swing.JButton();
        jButtonCos = new javax.swing.JButton();
        jButtonTan = new javax.swing.JButton();
        jButtonSinh = new javax.swing.JButton();
        jButtonCosh = new javax.swing.JButton();
        jButtonTanh = new javax.swing.JButton();
        jButtonXY = new javax.swing.JButton();
        jButtonX2 = new javax.swing.JButton();
        jButtonX3 = new javax.swing.JButton();
        jButtonBinary = new javax.swing.JButton();
        jButtonHexa = new javax.swing.JButton();
        jButtonOct = new javax.swing.JButton();
        jButtonFie = new javax.swing.JButton();
        jButtonCbr = new javax.swing.JButton();
        jButtonRund = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDisplayActionPerformed(evt);
            }
        });
        jTextFieldDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDisplayKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 226, 41));

        jButtonBackspace.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonBackspace.setText("<-");
        jButtonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackspaceActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBackspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, 110, 46));

        jButtonC.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 79, 52, 46));

        jButtonPlusOrMineze.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonPlusOrMineze.setText("+/-");
        jButtonPlusOrMineze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusOrMinezeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlusOrMineze, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 60, 43));

        jButtonMod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMod.setText("%");
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, 43));

        jButtonDivide.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonDivide.setText("/");
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 50, 43));

        jButtonMultiple.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonMultiple.setText("*");
        jButtonMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultipleActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMultiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 131, 52, 43));

        jButtonMin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonMin.setText("-");
        jButtonMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 131, 52, 43));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 52, 43));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 181, 52, 43));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 181, 52, 43));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 52, 43));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 230, 52, 43));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 230, 52, 43));

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonAdd.setText("+");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 180, 52, 92));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 281, 52, 43));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 281, 52, 43));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 281, 52, 43));

        jButtonEqual.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonEqual.setText("=");
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 281, 52, 95));

        jButtonDot.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 333, 52, 43));

        jButton0.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 333, 110, 43));

        jButtonLog.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonLog.setText("Log");
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 60, 43));

        jButtonLnX.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonLnX.setText("lnX");
        jButtonLnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLnXActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 60, 43));

        jButtonSquart1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonSquart1.setText("Squrt");
        jButtonSquart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSquart1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSquart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 60, 43));

        jButtonSin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonSin.setText("Sin");
        jButtonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, 43));

        jButtonCos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonCos.setText("Cos");
        jButtonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 60, 40));

        jButtonTan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonTan.setText("Tan");
        jButtonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 60, 40));

        jButtonSinh.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonSinh.setText("Sinh");
        jButtonSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinhActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 60, 43));

        jButtonCosh.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonCosh.setText("Cosh");
        jButtonCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCosh, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 60, 40));

        jButtonTanh.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonTanh.setText("Tanh");
        jButtonTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTanhActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 60, 40));

        jButtonXY.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonXY.setText("x^y");
        jButtonXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXYActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonXY, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 60, 43));

        jButtonX2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonX2.setText("x^2");
        jButtonX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonX2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 60, 43));

        jButtonX3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonX3.setText("x^3");
        jButtonX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonX3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 60, 43));

        jButtonBinary.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonBinary.setText("Bin");
        jButtonBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBinaryActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 60, 41));

        jButtonHexa.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonHexa.setText("Hex");
        jButtonHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHexaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHexa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 60, 43));

        jButtonOct.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonOct.setText("Oct");
        jButtonOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOctActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOct, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 60, 43));

        jButtonFie.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonFie.setText("7/22");
        jButtonFie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFieActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFie, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 60, 41));

        jButtonCbr.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonCbr.setText("Cbr");
        jButtonCbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCbrActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 60, 43));

        jButtonRund.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonRund.setText("Rund");
        jButtonRund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRundActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRund, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 60, 43));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDisplayActionPerformed

    private void jTextFieldDisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDisplayKeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)
            || (c==KeyEvent.VK_DELETE))){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDisplayKeyTyped

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setResizable(true);
        this.setSize(260, 450);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        this.setSize(490, 450);
        jTextFieldDisplay.setSize(445, 50);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackspaceActionPerformed
        String bsp = null;

        if(jTextFieldDisplay.getText().length()>0){
            StringBuilder strB = new StringBuilder(jTextFieldDisplay.getText());
            strB.deleteCharAt(jTextFieldDisplay.getText().length()-1);
            bsp = strB.toString();
            jTextFieldDisplay.setText(bsp);

        }
    }//GEN-LAST:event_jButtonBackspaceActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        jTextFieldDisplay.setText("");
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonPlusOrMinezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusOrMinezeActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = ops * (-1);
        jTextFieldDisplay.setText(String.valueOf(ops));

    }//GEN-LAST:event_jButtonPlusOrMinezeActionPerformed

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        firstnum = Double.parseDouble(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText(null);
        operations = ("%");
    }//GEN-LAST:event_jButtonModActionPerformed

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
        firstnum = Double.parseDouble(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText(null);
        operations = ("/");
    }//GEN-LAST:event_jButtonDivideActionPerformed

    private void jButtonMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultipleActionPerformed
        firstnum = Double.parseDouble(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText(null);
        operations = ("*");
    }//GEN-LAST:event_jButtonMultipleActionPerformed

    private void jButtonMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinActionPerformed
        firstnum = Double.parseDouble(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText(null);
        operations = ("-");
    }//GEN-LAST:event_jButtonMinActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String iNum=jTextFieldDisplay.getText() + jButton7.getText();
        jTextFieldDisplay.setText(iNum);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String iNum=jTextFieldDisplay.getText() + jButton8.getText();
        jTextFieldDisplay.setText(iNum);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String iNum=jTextFieldDisplay.getText() + jButton9.getText();
        jTextFieldDisplay.setText(iNum);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String iNum=jTextFieldDisplay.getText() + jButton4.getText();
        jTextFieldDisplay.setText(iNum);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String iNum=jTextFieldDisplay.getText() + jButton5.getText();
        jTextFieldDisplay.setText(iNum);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String iNum=jTextFieldDisplay.getText() + jButton6.getText();
        jTextFieldDisplay.setText(iNum);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        firstnum = Double.parseDouble(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText(null);
        operations = ("+");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String iNum=jTextFieldDisplay.getText() + jButton1.getText();
        jTextFieldDisplay.setText(iNum);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String iNum=jTextFieldDisplay.getText() + jButton2.getText();
        jTextFieldDisplay.setText(iNum);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String iNum=jTextFieldDisplay.getText() + jButton3.getText();
        jTextFieldDisplay.setText(iNum);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        String answer;
        secondnum = Double.parseDouble(jTextFieldDisplay.getText());
        if(operations == "+"){
            result = firstnum + secondnum;
            answer = String.format("%.2f", result);
            jTextFieldDisplay.setText(answer);
        }
        else if(operations == "-"){
            result = firstnum - secondnum;
            answer = String.format("%.2f", result);
            jTextFieldDisplay.setText(answer);
        }
        else if(operations == "*"){
            result = firstnum * secondnum;
            answer = String.format("%.2f", result);
            jTextFieldDisplay.setText(answer);
        }
        else if(operations == "/"){
            result = firstnum / secondnum;
            answer = String.format("%.2f", result);
            jTextFieldDisplay.setText(answer);
        }
        else if(operations == "%"){
            result = firstnum % secondnum;
            answer = String.format("%.2f", result);
            jTextFieldDisplay.setText(answer);
        }
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        if(!jTextFieldDisplay.getText().contains(".")){

            jTextFieldDisplay.setText(jTextFieldDisplay.getText() + jButtonDot.getText());
        }

    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        String iNum=jTextFieldDisplay.getText() + jButton0.getText();
        jTextFieldDisplay.setText(iNum);
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.log(ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void jButtonLnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLnXActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.log10(ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonLnXActionPerformed

    private void jButtonSquart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSquart1ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.sqrt(ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonSquart1ActionPerformed

    private void jButtonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.sin(ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonSinActionPerformed

    private void jButtonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCosActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.cos(ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonCosActionPerformed

    private void jButtonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTanActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.tan(ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonTanActionPerformed

    private void jButtonSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinhActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.sinh(ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonSinhActionPerformed

    private void jButtonCoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoshActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.cosh(ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonCoshActionPerformed

    private void jButtonTanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTanhActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.tanh(ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonTanhActionPerformed

    private void jButtonXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXYActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.pow(ops,ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonXYActionPerformed

    private void jButtonX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonX2ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = (ops * ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonX2ActionPerformed

    private void jButtonX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonX3ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = (ops * ops * ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonX3ActionPerformed

    private void jButtonBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBinaryActionPerformed
        int a = Integer.parseInt(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText(Integer.toString(a,2));
    }//GEN-LAST:event_jButtonBinaryActionPerformed

    private void jButtonHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHexaActionPerformed
        int a = Integer.parseInt(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText(Integer.toString(a,16));
    }//GEN-LAST:event_jButtonHexaActionPerformed

    private void jButtonOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOctActionPerformed
        int a = Integer.parseInt(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText(Integer.toString(a,8));
    }//GEN-LAST:event_jButtonOctActionPerformed

    private void jButtonFieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFieActionPerformed
        double ops;
        ops = 3.14159265358;
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonFieActionPerformed

    private void jButtonCbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCbrActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.cbrt(ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonCbrActionPerformed

    private void jButtonRundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRundActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        ops = Math.round(ops);
        jTextFieldDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonRundActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
      this.setSize(260, 450);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBackspace;
    private javax.swing.JButton jButtonBinary;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCbr;
    private javax.swing.JButton jButtonCos;
    private javax.swing.JButton jButtonCosh;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonFie;
    private javax.swing.JButton jButtonHexa;
    private javax.swing.JButton jButtonLnX;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonMin;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonMultiple;
    private javax.swing.JButton jButtonOct;
    private javax.swing.JButton jButtonPlusOrMineze;
    private javax.swing.JButton jButtonRund;
    private javax.swing.JButton jButtonSin;
    private javax.swing.JButton jButtonSinh;
    private javax.swing.JButton jButtonSquart1;
    private javax.swing.JButton jButtonTan;
    private javax.swing.JButton jButtonTanh;
    private javax.swing.JButton jButtonX2;
    private javax.swing.JButton jButtonX3;
    private javax.swing.JButton jButtonXY;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextFieldDisplay;
    // End of variables declaration//GEN-END:variables
}
